### PR TITLE
fix: mount bind revanced.apk from magisk's mirror

### PR DESCRIPTION
**Pull request by HuskyDG**
Some banking apps already detect the mountpoint of youtube base apk to determine device is rooted. So mount bind from magisk's mirror to trigger magisk unmount and let it hidden along with MagiskHide or hiding modules.

### CODE REVIEW

**Comment by Sculas** [comment]
@oSumAtrIX #32

**Comment by oSumAtrIX** [comment]
@Sculas what do you mean?

**Comment by Sculas** [comment]
> @Sculas what do you mean?

In PR #32, you said this:

> This PR would force everyone to use Magisk. Currently, the only dependency is the super-user for the root variant. Some people have a super-user but do not have Magisk, for that reason we can not merge this.

Is this still the case? Won't this PR make it Magisk-only?

**Comment by oSumAtrIX** [comment]
Yes, it would constrain it to Magisk, which is not too bad I would assume, due to the majority using Magisk. I'll let you decide.

**Comment by HuskyDG** [comment]
I don't expect this to be added. That's your two desicion 😉

**Comment by Sculas** [comment]
I'm fine with merging this. Support for other rooting methods is something for the future, let's get this fixed first.

**Comment by Sculas** [comment]
Thank you for this PR!

**Comment by HuskyDG** [comment]
> I'm fine with merging this. Support for other rooting methods is something for the future, let's get this fixed first.

For other root solution, you need to use `init.d`

**Pull request merged**
