### PR TITLE
fix: dont crash on a null when resource patching is disabled

### PR DESCRIPTION
**Pull request by bogadana**
needs https://github.com/revanced/revanced-patcher/pull/64

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Please bump the version when https://github.com/revanced/revanced-patcher/pull/64 finishes to release

**Comment by bogadana** [comment]
done

**Comment by ponces** [comment]
Could you please merge this?

> Please bump the version when [revanced/revanced-patcher#64](https://github.com/revanced/revanced-patcher/pull/64) finishes to release

**Comment by bogadana** [comment]
Removed the version change since it conflicts now

**Pull request merged**
