### PR TITLE
feat: added new --compatibility option to lists compatibilities

### PR DESCRIPTION
**Pull request by EdgE790**
Added new --compatibility option to the CLI that will list compatibilities for every patch with packages and list of versions that this patch currently compatible with.

Usage: `java -jar cli.jar --compatibility -b patches.jar`
Result on current version of patches (1.10.4)
```
INFO:      music                    codecs-unlock       5.03.50
INFO:      music         exclusive-audio-playback       5.03.50
INFO:      music             tasteBuilder-remover       5.03.50
INFO:      music           upgrade-button-remover       5.03.50
INFO:      music                  background-play       5.03.50
INFO:    youtube                      general-ads       17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34
INFO:    youtube                        video-ads       17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34
INFO:    youtube                  seekbar-tapping       17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34
INFO:    youtube                           amoled       17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34
INFO:    youtube                  premium-heading
INFO:    youtube                  custom-branding
INFO:    youtube                 hide-cast-button
INFO:    youtube            disable-create-button       17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34
INFO:    youtube        disable-fullscreen-panels       17.23.35, 17.23.36, 17.24.34
INFO:    youtube               minimized-playback       17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34
INFO:    youtube               old-quality-layout       17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34
INFO:    youtube            disable-shorts-button       17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34
INFO:    youtube                   microg-support       17.14.35, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34
```

Why this feature should be merged?
Currently it's not clear which patches are available for different packages and their versions.
Without browsing source code of patches, it's not clear which version should be used as a base for patching.
This feature will make it clear which patch compatible with different versions / packages, especially when they are used as prebuild packages as listed in documentation page: https://github.com/revanced/revanced-documentation/wiki/Downloading-prebuilt-packages

I believe this feature can help, e.g.: https://github.com/orgs/revanced/discussions/248

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Nice. Instead of adding a new option which almost functions the same as --list, you should simply integrate this into --list.

**Comment by EdgE790** [comment]
Not sure about this, due to quite recent changes --list option shows patch descriptions, while compatibility is not.
Merging them will create too bulky output which will make it harder to look for descriptions / compatible versions.

**Comment by oSumAtrIX** [comment]
Showing information about patches is kind of part of when listing them. You can add some options to the listing command for example --list --with-compatibility --package and so on.

**Comment by EdgE790** [comment]
Replaced --compatibility option to 3 new additional options to --list:

- `--with-versions`   default: false
- `--with-packages`   default: false
- `--with-descriptions`  default: true

Results:

`--list` works almost the same as it was (except padding to the right of patch names) 
```
--list

INFO:             codecs-unlock	Enables more audio codecs. Usually results in better audio quality but may depend on song and device. 
INFO:  exclusive-audio-playback	Add the option to play music without video. 
INFO:      tasteBuilder-remover	Removes the "Tell us which artists you like" card from the Home screen. The same functionality can be triggered from the settings anyway. 
INFO:    upgrade-button-remover	Remove the upgrade tab from the pivot bar in YouTube music. 
INFO:           background-play	Enable playing music in the background. 
INFO:               general-ads	Patch to remove general ads in bytecode. 
INFO:                 video-ads	Patch to remove ads in the YouTube video player. 
INFO:           seekbar-tapping	Enable tapping on the seekbar of the YouTube player. 
INFO:                    amoled	Enables pure black theme. 
INFO:           premium-heading	Show the premium branding on the the YouTube home screen. 
INFO:           custom-branding	Change the branding of YouTube. 
INFO:          hide-cast-button	Patch to hide the cast button. 
INFO:     disable-create-button	Disable the create button. 
INFO: disable-fullscreen-panels	Disable comments panel in fullscreen view. 
INFO:        minimized-playback	Enable minimized and background playback. 
INFO:        old-quality-layout	Enable the original quality flyout menu. 
INFO:     disable-shorts-button	Hide the shorts button. 
INFO:            microg-support	Patch to allow YouTube ReVanced to run without root and under a different package name. 
```
`--list --with-versions` contains descriptions, because descriptions are enabled by default.
```
--list --with-versions

INFO:             codecs-unlock	Enables more audio codecs. Usually results in better audio quality but may depend on song and device.	5.03.50 
INFO:  exclusive-audio-playback	Add the option to play music without video.	5.03.50 
INFO:      tasteBuilder-remover	Removes the "Tell us which artists you like" card from the Home screen. The same functionality can be triggered from the settings anyway.	5.03.50 
INFO:    upgrade-button-remover	Remove the upgrade tab from the pivot bar in YouTube music.	5.03.50 
INFO:           background-play	Enable playing music in the background.	5.03.50 
INFO:               general-ads	Patch to remove general ads in bytecode.	17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:                 video-ads	Patch to remove ads in the YouTube video player.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:           seekbar-tapping	Enable tapping on the seekbar of the YouTube player.	17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:                    amoled	Enables pure black theme.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:           premium-heading	Show the premium branding on the the YouTube home screen.	 
INFO:           custom-branding	Change the branding of YouTube.	 
INFO:          hide-cast-button	Patch to hide the cast button.	 
INFO:     disable-create-button	Disable the create button.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: disable-fullscreen-panels	Disable comments panel in fullscreen view.	17.23.35, 17.23.36, 17.24.34 
INFO:        minimized-playback	Enable minimized and background playback.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:        old-quality-layout	Enable the original quality flyout menu.	17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:     disable-shorts-button	Hide the shorts button.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:            microg-support	Patch to allow YouTube ReVanced to run without root and under a different package name.	17.14.35, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
```

Descriptions can be turned off by using `--with-descriptions=false`
```
 -l --with-versions --with-descriptions=false --with-packages
INFO:      music	            codecs-unlock	5.03.50 
INFO:      music	 exclusive-audio-playback	5.03.50 
INFO:      music	     tasteBuilder-remover	5.03.50 
INFO:      music	   upgrade-button-remover	5.03.50 
INFO:      music	          background-play	5.03.50 
INFO:    youtube	              general-ads	17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	                video-ads	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	          seekbar-tapping	17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	                   amoled	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	          premium-heading	 
INFO:    youtube	          custom-branding	 
INFO:    youtube	         hide-cast-button	 
INFO:    youtube	    disable-create-button	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	disable-fullscreen-panels	17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	       minimized-playback	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	       old-quality-layout	17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	    disable-shorts-button	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	           microg-support	17.14.35, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
```
All available flags enabled look like this:
```
-l --with-versions --with-packages
INFO:      music	            codecs-unlock	Enables more audio codecs. Usually results in better audio quality but may depend on song and device.	5.03.50 
INFO:      music	 exclusive-audio-playback	Add the option to play music without video.	5.03.50 
INFO:      music	     tasteBuilder-remover	Removes the "Tell us which artists you like" card from the Home screen. The same functionality can be triggered from the settings anyway.	5.03.50 
INFO:      music	   upgrade-button-remover	Remove the upgrade tab from the pivot bar in YouTube music.	5.03.50 
INFO:      music	          background-play	Enable playing music in the background.	5.03.50 
INFO:    youtube	              general-ads	Patch to remove general ads in bytecode.	17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	                video-ads	Patch to remove ads in the YouTube video player.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	          seekbar-tapping	Enable tapping on the seekbar of the YouTube player.	17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	                   amoled	Enables pure black theme.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	          premium-heading	Show the premium branding on the the YouTube home screen.	 
INFO:    youtube	          custom-branding	Change the branding of YouTube.	 
INFO:    youtube	         hide-cast-button	Patch to hide the cast button.	 
INFO:    youtube	    disable-create-button	Disable the create button.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	disable-fullscreen-panels	Disable comments panel in fullscreen view.	17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	       minimized-playback	Enable minimized and background playback.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	       old-quality-layout	Enable the original quality flyout menu.	17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	    disable-shorts-button	Hide the shorts button.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO:    youtube	           microg-support	Patch to allow YouTube ReVanced to run without root and under a different package name.	17.14.35, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 

```

**Comment by oSumAtrIX** [comment]
What are the patch names padded to the right?

**Comment by EdgE790** [comment]
I chose random directon, lol. I can change it to right padding if you like.
```
INFO: music     	            codecs-unlock	Enables more audio codecs. Usually results in better audio quality but may depend on song and device.	5.03.50 
INFO: music     	 exclusive-audio-playback	Add the option to play music without video.	5.03.50 
INFO: music     	     tasteBuilder-remover	Removes the "Tell us which artists you like" card from the Home screen. The same functionality can be triggered from the settings anyway.	5.03.50 
INFO: music     	   upgrade-button-remover	Remove the upgrade tab from the pivot bar in YouTube music.	5.03.50 
INFO: music     	          background-play	Enable playing music in the background.	5.03.50 
INFO: youtube   	              general-ads	Patch to remove general ads in bytecode.	17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	                video-ads	Patch to remove ads in the YouTube video player.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	          seekbar-tapping	Enable tapping on the seekbar of the YouTube player.	17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	                   amoled	Enables pure black theme.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	          premium-heading	Show the premium branding on the the YouTube home screen.	 
INFO: youtube   	          custom-branding	Change the branding of YouTube.	 
INFO: youtube   	         hide-cast-button	Patch to hide the cast button.	 
INFO: youtube   	    disable-create-button	Disable the create button.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	disable-fullscreen-panels	Disable comments panel in fullscreen view.	17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	       minimized-playback	Enable minimized and background playback.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	       old-quality-layout	Enable the original quality flyout menu.	17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	    disable-shorts-button	Hide the shorts button.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	           microg-support	Patch to allow YouTube ReVanced to run without root and under a different package name.	17.14.35, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
```

**Comment by EdgE790** [comment]
And with right padding for patch names: 
```
INFO: music     	codecs-unlock            	Enables more audio codecs. Usually results in better audio quality but may depend on song and device.	5.03.50 
INFO: music     	exclusive-audio-playback 	Add the option to play music without video.	5.03.50 
INFO: music     	tasteBuilder-remover     	Removes the "Tell us which artists you like" card from the Home screen. The same functionality can be triggered from the settings anyway.	5.03.50 
INFO: music     	upgrade-button-remover   	Remove the upgrade tab from the pivot bar in YouTube music.	5.03.50 
INFO: music     	background-play          	Enable playing music in the background.	5.03.50 
INFO: youtube   	general-ads              	Patch to remove general ads in bytecode.	17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	video-ads                	Patch to remove ads in the YouTube video player.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	seekbar-tapping          	Enable tapping on the seekbar of the YouTube player.	17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	amoled                   	Enables pure black theme.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	premium-heading          	Show the premium branding on the the YouTube home screen.	 
INFO: youtube   	custom-branding          	Change the branding of YouTube.	 
INFO: youtube   	hide-cast-button         	Patch to hide the cast button.	 
INFO: youtube   	disable-create-button    	Disable the create button.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	disable-fullscreen-panels	Disable comments panel in fullscreen view.	17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	minimized-playback       	Enable minimized and background playback.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	old-quality-layout       	Enable the original quality flyout menu.	17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	disable-shorts-button    	Hide the shorts button.	17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
INFO: youtube   	microg-support           	Patch to allow YouTube ReVanced to run without root and under a different package name.	17.14.35, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34 
```

**Pull request merged**
