### PR TITLE
fix: listing patches requires input apk

### LINKED ISSUE #87: problem: listing patches requires input apk again
# 🐞 Issue

i wanna look at the changes in patches file (to include/exclude new patches), but cli gives me an error Error: Missing required argument(s): --apk=<inputFile>

# ⚙ Reproduce
i use revanced aur package. command: revanced-cli (just alias to java -jar /usr/share/revanced/revanced-cli.jar) -b /usr/share/revanced/revanced-patches.jar -l

# 🛠 Solution
selecting vanilla youtube input apk is the solution

# ⚠ Additional context

### PR DESCRIPTION
**Pull request by Itroublve**
Fixes #87

### CODE REVIEW

**Comment by TheJeterLP** [comment]
You have to add a second commit to this that does nothing. Otherwise your PR can't be squashed :(

**Comment by bogadana** [comment]
or just have a semantic commit in the first place

**Comment by Itroublve** [comment]
> You have to add a second commit to this that does nothing. Otherwise your PR can't be squashed :(

Yes, I'm not done yet anyways c:

**Comment by Itroublve** [comment]
Alright, fixed... `--uninstall` now takes in the apk itself instead of needing other params, makes more sense as well considering you're just specifying what you want to uninstall.

**Comment by TheJeterLP** [comment]
You should add a way of not providing an APK but providing the package name as a string. There might be some applications where the package name gets changed in a rooted phone too

**Comment by Itroublve** [comment]
> You should add a way of not providing an APK but providing the package name as a string. There might be some applications where the package name gets changed in a rooted phone too

Sure, just a moment.

**Comment by oSumAtrIX** [comment]
The code looks like it is working around the current code and should instead be adjusted to properly support this feature.

**Comment by Itroublve** [comment]
I'll fix this and create a new PR with latest changes to avoid issues.

**Pull request closed without merging**
