### PR TITLE
Install ReVanced(Root) as Magisk module

### PR DESCRIPTION
**Pull request by yuma2b**
・We can uninstall revanced easier through Magisk App.
This is necessary for usability.
[Magisk App]

・Install Revanced in Magisk module folder
[Magisk Official Guides](https://topjohnwu.github.io/Magisk/guides.html)
https://github.com/revanced/revanced-cli/blob/d98269d3ce92c3a0ed2f09d338aa1b4fd384e38e/src/main/kotlin/app/revanced/utils/adb/Constants.kt#L17-L26
https://github.com/revanced/revanced-cli/blob/d98269d3ce92c3a0ed2f09d338aa1b4fd384e38e/src/main/kotlin/app/revanced/utils/adb/Constants.kt#L69-L78

・To prevent trouble, old mount scripts in mobile will be removed, automatically.
https://github.com/revanced/revanced-cli/blob/d98269d3ce92c3a0ed2f09d338aa1b4fd384e38e/src/main/kotlin/app/revanced/utils/adb/Constants.kt#L41-L45
https://github.com/revanced/revanced-cli/blob/d98269d3ce92c3a0ed2f09d338aa1b4fd384e38e/src/main/kotlin/app/revanced/utils/adb/Adb.kt#L34-L35
Please adjust the code. Thanks.

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
This PR would force everyone to use Magisk. Currently, the only dependency is the super-user for the root variant. Some people have a super-user but do not have Magisk, for that reason we can not merge this. Always create an issue before you create a PR!

**Comment by tillnelown** [comment]
Am i reading this wrong or does this break multiple patched app installs? Does installing Youtube and then Youtube Music overwrite each other because the scripts seem to be.

**Comment by oSumAtrIX** [comment]
The script creates separate mount scripts for each application by its package name.

**Comment by HuskyDG** [comment]
> This PR would force everyone to use Magisk. Currently, the only dependency is the super-user for the root variant. Some people have a super-user but do not have Magisk, for that reason we can not merge this. Always create an issue before you create a PR!

Think about this: other root does not have `/data/adb/post-fs-data.d` and `/data/adb/service.d`

**Pull request closed without merging**
