### PR TITLE
Use the `/data/adb/magisk/busybox` from Magisk wherever possible

### PR DESCRIPTION
**Pull request by tillnelown**
Remember, this is untested. I checked that each command exists and runs in the busysbox but i didn't install it to /data/adb/

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Please test it before creating a PR

**Comment by tillnelown** [comment]
Currently i have no time but I'll test it later, though as [Lucaskyy](https://github.com/Lucaskyy) said this may not be the cause of the problem.

**Comment by oSumAtrIX** [comment]
Hence I converted it to a draft, only make a PR if you know its ready to get merged

**Comment by tillnelown** [comment]
> Every single shell script running in the context of Magisk will be executed in BusyBox’s ash shell with standalone mode enabled. For what is relevant to 3rd party developers, this includes **all boot scripts** and module installation scripts.

The current script already uses ash and its busybox, this Draft will not actually change anything so I will close it.

**Pull request closed without merging**
